# Generated by Django 3.1.2 on 2020-10-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=255, verbose_name='图片链接')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='图片名称')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
                'db_table': 'tb_link',
            },
        ),
    ]
